### PR TITLE
Fixes npm run unit

### PR DESCRIPTION
**Pull request by kiltec**
When I prepared to work on https://github.com/ratiw/vuetable-2/issues/152 I noticed that the tests were not working.
This PR fixes `npm run unit`

### CODE REVIEW

**Comment by kiltec** [comment]
Don't merge this, just learned that I need to mock using the vueloader as explained here:
https://vue-loader.vuejs.org/en/workflow/testing-with-mocks.html

Will make the necessary changes tomorrow.

**Comment by kiltec** [comment]
I've changed the method of mocking Axios.
Note that Javascript isn't my first language, so if something seems odd, please let me know! :)

**Comment by ratiw** [comment]
@kiltec Thanks for the PR. Unfortunately, I'm still unable to run `npm run unit` because of the following error.
```shell
WARN [plugin]: Error during loading ".../vuetable-2/node_modules/karma-phantomjs-launcher" plugin:
  Path must be a string. Received null
```

**Comment by kiltec** [comment]
@ratiw Weird. Will try to find out what's up with that. I don't get that warning, so  that's going to be interesting! ☺️

**Comment by ratiw** [comment]
@kiltec Please also note that, I've updated the build configuration according to what has been generated using `vue-cli` v.2.8.0 yesterday. If you can help fix this, it would really help encourage me to start the testing again.

**Comment by kiltec** [comment]
Ok, I get a different error after merging your changes into this branch.
I've looked at eced8b7 and a lot of stuff related to webpack has changed but there are no changes to test/unit/karma.conf.js so that is most likely the reason for the tests having stopped to work.

I'm going to try and find a solution!

**Comment by kiltec** [comment]
For the record, this is the error I get:
```
# npm run unit
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.0
npm info lifecycle vuetable-2@1.6.1~preunit: vuetable-2@1.6.1
npm info lifecycle vuetable-2@1.6.1~unit: vuetable-2@1.6.1

> vuetable-2@1.6.1 unit /usr/src/app
> cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'vue'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           vue: ...
         }
       })
     ]
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence? }
   Options affecting the normal modules (`NormalModuleFactory`).
    at webpack (/usr/src/app/node_modules/webpack/lib/webpack.js:19:9)
    at new Plugin (/usr/src/app/node_modules/karma-webpack/lib/karma-webpack.js:67:16)
    at invoke (/usr/src/app/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/usr/src/app/node_modules/di/lib/injector.js:59:20)
    at get (/usr/src/app/node_modules/di/lib/injector.js:48:43)
    at /usr/src/app/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/usr/src/app/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/usr/src/app/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/usr/src/app/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (/usr/src/app/node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke (/usr/src/app/node_modules/di/lib/injector.js:75:15)
    at get (/usr/src/app/node_modules/di/lib/injector.js:48:43)
    at /usr/src/app/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
28 05 2017 19:57:18.014:ERROR [preprocess]: Can not load "webpack"!
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'vue'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           vue: ...
         }
       })
     ]
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence? }
   Options affecting the normal modules (`NormalModuleFactory`).
    at webpack (/usr/src/app/node_modules/webpack/lib/webpack.js:19:9)
    at new Plugin (/usr/src/app/node_modules/karma-webpack/lib/karma-webpack.js:67:16)
    at invoke (/usr/src/app/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/usr/src/app/node_modules/di/lib/injector.js:59:20)
    at get (/usr/src/app/node_modules/di/lib/injector.js:48:43)
    at /usr/src/app/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/usr/src/app/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/usr/src/app/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/usr/src/app/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (/usr/src/app/node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke (/usr/src/app/node_modules/di/lib/injector.js:75:15)
    at get (/usr/src/app/node_modules/di/lib/injector.js:48:43)
    at /usr/src/app/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
```

**Comment by kiltec** [comment]
@ratiw  Tests run again now - well, in my environment, I've never got the error you mentioned, so please let me know if you still cannot run them.

Note that you should run `yarn install´ or `npm install` before this will work.

**Comment by ratiw** [comment]
Thanks, @kiltec. Manage to get it running successfully with `yarn upgrade`. But having a weird `ERROR LOG: `[Vue Warn]: ...`. Have you got that too?

**Comment by kiltec** [comment]
Thanks for merging!

Are you referring to
```
ERROR LOG: '[Vue warn]: Missing required prop: "fields"

found in

---> <Vuetable> at /usr/src/app/src/components/Vuetable.vue
       <Root>'
```

That one is due to an old test https://github.com/ratiw/vuetable-2/blob/master/test/unit/specs/Vuetable.spec.js#L41-L53
Not sure if it is a good practice to test it that way, maybe you could do it differently.

**Pull request merged**
