### PR TITLE
#153 Update webpack.build.config to webpack-2 and vue-cli webpack file format

### PR DESCRIPTION
**Pull request by cristijora**
This is just an update to webpack 2 and general vue-cli config style. Settings for non-minified version are not done yet. 

Update: Added the necessary changes to build minified and non minified versions of the js bundle
1. Run `npm run bundle` which will generate 2 files
 - vuetable-2.js (minified version)
 - vuetable-2-full.js (non minified version)

You can change the naming for the second file here
```js
if(process.env.MINIFY && process.env.MINIFY === "false"){
  jsFileName = "vuetable-2-full.js"
}
```
I wouldn't change the naming for the minified since it's already used by people.

### CODE REVIEW

**Comment by ratiw** [comment]
@cristijora Many thanks as always.  🙏 👍

**Comment by cristijora** [comment]
Note that, the output will contain render functions for templates so the output file (non-minified) might still be very different from the .vue file. At least the namings and functions from the script part are kept the same so it's easier for people to get an idea of what happened or what's the error.

Oh and all the output files can be accessed on unpkg after a new npm publish
https://unpkg.com/vuetable-2@1.6.0/dist/

**Comment by ratiw** [comment]
@cristijora When running `yarn run bundle`, it always create the file name `[object Object]` in the `dist` directory. Can you please have a look at this?

**Comment by cristijora** [comment]
This file is a webpack stats file. You can upload it to some website and see the content of your bundle https://chrisbateman.github.io/webpack-visualizer/ This file can be ignored in git

**Comment by ratiw** [comment]
I see. But can we force webpack to name it something other than [`object Object`](https://github.com/ratiw/vuetable-2/blob/develop/dist/%5Bobject%20Object%5D)?

**Comment by cristijora** [comment]
Change 
```
new StatsPlugin({
      fileName: "../stats.json",
      chunkModules: true
    })
```

to 
```
new StatsPlugin('stats.json')
```

In webpack.build.config.js

**Pull request merged**
