### PR TITLE
Improve `api-mode = false` experience

### PR DESCRIPTION
**Pull request by jwkicklighter**
This PR introduces 2 minor changes that make a big difference for data mode, especially helping with Vuex interactivity:

1. Sorting the table will no longer call `loadData()` if not in api mode. This means that clicking on a header will not wipe the data inside the table. There is the data-manager route, but that did not work for my use case. What this allows is to set `sortParams` from the parent component, pass it as a prop to `vuetable`, and then watch the `sortParams` in the parent to see any changes to the sorting. i.e. sorting can be manually accomplished in `api-mode = false` without having to use a data-manager (which means it can be async, since data-manager requires you to have a synchronous transformation).

2. The `data` prop is now reactive (well, it is watched and will refresh the table when it is changed). This allows passing an array/object into the `data` prop, and simply changing that array/object in order to update the table.

My reasoning behind these changes is to make the data mode be more friendly for Vuex. The second change in particular is very nice because `data` can simply be boud to a Vuex getter and the table will react to any Vuex state changes. The first change just provides an async mechanism to monitor the sorting so you can, for instance, fire off a Vuex action.

If this is merged, I would love to help create some documentation for the Wiki/docs that describes a basic example of using Vuex. Getting Vuex and Vuetable to play nicely without at least the second change was proving very difficult.

### CODE REVIEW

**Comment by wa05** [comment]
Thanks for the review, is already the Vuex example in the docs or where I can find one ?

**Comment by jwkicklighter** [comment]
@wa05 I did not write up any example as it's basically just under-the-hood improvements. If you pass data to vuetable using the `data` prop, Vuetable now watches that and redraws reactively if the data changes. And using the columns for sorting no longer clobbers the Vuetable data in api-mode=false

**Comment by ratiw** [comment]
@jwkicklighter Just release it in v1.7.1. Really looking forward to your doc on using it with Vuex as I don't have much experience with it. 

Cheers! :)

**Comment by ratiw** [comment]
@jwkicklighter I've found one problem in the first improvement you've made by not calling `loadData()` when not in API mode. The `data-manager` is no longer work as expected because it was not called at all and this causes behavior change in Vuetable. I think I would also need to also check that the `data-manager` is also not set before ignoring the call to `loadData()`, but I have no way to check that it will still work in your case. Can you please help verifying that it is still work correctly in your case?

```javascript
  if (this.apiMode && this.dataManager === null) {
    this.loadData()
  }
```

**Pull request merged**
