### PR TITLE
Implemented custom transition classes for table rows

### PR DESCRIPTION
**Pull request by RZetko**
Vuetable component now contains 4 new props which we can use to apply custom transition classes on table rows entering/leaving table.

- rowTransitionEnterClass
- rowTransitionLeaveClass
- rowTransitionEnterActiveClass
- rowTransitionLeaveActiveClass

### CODE REVIEW

**Comment by ratiw** [comment]
Can you please provide sample code in codepen or jsfiddle? The code looks a bit strange to me as I thought you're supposed to apply those attributes in the `<transition>` tag but instead you apply it to `<tbody>`.
I need to see how it will look to understand it.

**Comment by RZetko** [comment]
Sure, here's pen I created https://codepen.io/anon/pen/MVQNpP. I hope it will be enough. It's based on your codepen from vuetable-2 1.6.0 version mentioned in readme.md with following changes:

- included animate.css from CDN for animations
- ran npm run build on my local branch of vuetable-2 (develop branch) with implemented changes from PR (version that I submitted for PR)
- put built unminifed vuetable-2-full.js to javascript section in codepen
- added row-transition-enter-active-class and row-transition-leave-active-class props with animate.css classes (animated and zoomIn CSS classess)

There are no other changes. I also thought that simple `<transition>` tag would suffice but you can't use it with `v-for` items and I needed to implement it this way. I have no idea how it is actually implemented internally in vue js but all it should do is create event listeners (enter/leave list) for all the keyed elements from v-for (that's why they need unique keys) and add user specified CSS classes on items entering/leaving list.

There's also one thing I didn't implement to keep backwards compatibility - enter-to-class and leave-to-class (https://vuejs.org/v2/guide/transitions.html#Custom-Transition-Classes). They are only available for vue js 2.1.8+.

If you have any more questions just let me know, I'll try to answer them as best as I can.

Thank you

**Comment by ratiw** [comment]
@RZetko I've tried your PR during the weekend but somehow it will cause detail row transition unusable, and this would break the existing code. Also, it will only work the first time the data is loaded. So, I can only see the transition on the first page and it will not happen again when moving the other pages.

**Comment by RZetko** [comment]
I tried to test it out as much as possible in my project but there are things that I didn't try because of scope of vuetable-2. It's unfortunate that it breaks detail row transitions. I don't know any other way to implement (I'll try to look into it some more but I don't see any way without completely changing structure of vuetable) it so I'll probably close the PR.

Thank you for help.

**Comment by ratiw** [comment]
In [v2.0](https://github.com/ratiw/vuetable-2/tree/next) of Vuetable-2, the template structure has changed quite a lot as I'm introducing more internal components into it for the sake of extensibility. The only remaining thing will the refactoring of table body to make data row extensible. This should (hopefully) also include data row transition as well, but it is something I need to research on quite a bit.

**Comment by RZetko** [comment]
I'll wait for v2 then hope that in/out animations will make it in. Thank you.

**Comment by joernroeder** [comment]
@ratiw i'm currently looking for a good vue table lib and your seems to be one of the best (most complete featureset) out there – thanks for putting so much work into it! But for me (custom) enter/leave transitions of rows are an essential part of my checklist. therefore i'm asking if you could make any progress adding those to the upcoming v2 version.
thanks in advance!

**Pull request closed without merging**
