### PR TITLE
ApiUrl watcher fix + Data watcher

### PR DESCRIPTION
**Pull request by fabiorizzello**

### CODE REVIEW

**Comment by ratiw** [comment]
@fabiorizzello Thanks for the PR, but can you please state the purpose of this fix and how it's solved your problem.

**Comment by fabiorizzello** [comment]
@ratiw 
See #110 for the api-url fix

I've added a watcher for the data prop because i want to bind **my data** to the **table data**.
This way if i remove an element i can do an ajax call to my apis, then i can manually remove the element from **my data** then the deletion will be reflected to the **table data** thanks to the watcher.
It can be a deletion like an insert or edit.

Actually after this pull request i've seen that the data property is not fully implemented yet. For example the sort doesn't work. But i think it's still a work in progress right?

**Comment by ratiw** [comment]
@fabiorizzello Right now, the `data` property is quite limited in its functionality. The server related functions like sorting, searching/filtering, and pagination are still not supported on the client side. And I have NO plan to add it any time soon.

**Comment by ratiw** [comment]
@fabiorizzello To prevent confusion, I'll have to close this PR for the time being. Sorry for this. But I do really appreciate your contribution.

**Pull request closed without merging**
