### PR TITLE
Added support for function in field dataClass

### PR DESCRIPTION
**Pull request by topclaudy**
Now we can use function to format cells according to `rowData` and/or `rowIndex`. The function accepts the `rowData` and the `rowIndex` as arguments.

Ex:

```
{
        name: 'price',
        title: 'Price',
        dataClass: function(rowData, rowIndex){
            if(rowData.change < 0){
                return 'bg-red'
            } else {
                return 'bg-green'
            }
        }   
 }
```

### CODE REVIEW

**Comment by ratiw** [comment]
@topclaudy Thanks for the contribution. It's look useful and I might incorporate this idea into the next version of Vuetable. However, I might not pass item and item index into the function.

**Comment by topclaudy** [comment]
@ratiw Thanks for the feedback. How would we access the row data if we don't pass item into the function?

**Comment by ratiw** [comment]
@topclaudy Logically, `dataClass` is the attribute of a column. It should not has access to the "row" data. 

I would instead pass the field definition and "value" of that field to the function.

If you would like to change the background of the row, you should instead use [`row-class`](https://github.com/ratiw/vuetable-2/wiki/Vuetable-Properties#-row-class) prop, which has access to row data and row index. See example [here](https://github.com/ratiw/vuetable-2/wiki/Vuetable-Properties#-row-class).

**Comment by topclaudy** [comment]
@ratiw Good point! In my situation, I needed to set the class based on the value of another column (see example). Hence the reason I pass`rowData` as parameter.

**Comment by mrin9** [comment]
+1 for the feature request

**Comment by yusufdemir** [comment]
+1

**Comment by zeshanshani** [comment]
+1

**Comment by topclaudy** [comment]
@ratiw doesn't seem open to the idea.

**Comment by zeshanshani** [comment]
That's a pity. It would make things much more powerful. I'm starting to find some alternate table plugin already...

@ratiw can you consider it, please? Or perhaps give an alternate option where user can modify the output value of a single table cell? Scoped slots perhaps?

**Comment by ratiw** [comment]
Well, it's not that I'm not open to the idea. Whenever I have time to update the library, I'm always thinking about this specific issue. I'm more incline implement this into Vuetable, but most of my time 
has been focusing on update the documentation for the next version of Vuetable. Then, it will be
other pending stuffs, both PRs and issues.

The recommended solution is to use [Field Component](https://upbeat-montalcini-9fc063.netlify.com/guide/creating-field-component.html) in v2.0 of Vuetable, which is available in the `next` branch. With Field Component, you'll have complete control over the `th` and `td` element. It is much more powerful and can easily be reused.

Unfortunately, time is not always on my side. There is so much I can do with the time that I can work on Vuetable.

**Comment by zeshanshani** [comment]
@ratiw thanks for your response!

Field Component sounds like a great idea. Can't want to start using it. I'm implementing Vue Table on a large cryptocurrency site currently and it would be super cool if you can give a rough timeline for the next release? This way I can perhaps use the `next` branch and later update to the stable release. 

Thanks already for this great plugin btw. After the documentation is officially released, it would be super awesome. Similar to how Bootstrap Vue is: https://bootstrap-vue.js.org/

**Comment by ratiw** [comment]
@zeshanshani You can start using them now, just follow the instruction in the documentation [here](https://upbeat-montalcini-9fc063.netlify.com/guide/getting-started.html). It has been in the alpha stage for quite sometime already. The beta is quite stable in my opinion. I push it out so that people can try and give me some feedbacks. A few more features need to be added when I have time.

**Comment by zeshanshani** [comment]
@ratiw that's awesome! I'll give it a try then. Thank you! :)

**Comment by zeshanshani** [comment]
@ratiw feedback: 

I used the `next` release and this is working really well. So here's what I've loved so far:

- Simplicity in importing as ES6 module. I just had to use this line to pull both table as well as pagination: `import {Vuetable, VuetablePagination} from 'vuetable-2'`

- Each and every row cell's value can be changed and even put custom HTML to it by simply using field slots (THIS IS HUGE): https://upbeat-montalcini-9fc063.netlify.com/guide/special-field.html#field-slot

- Documentation - this is one of the best things happened to Vuetables-2 plugin. 

So a big thank you for making these updates 🙏

**Pull request closed without merging**
