### PR TITLE
Add splitSortOrder option

### PR DESCRIPTION
**Pull request by ghost**
Some API REST endpoints do not accept the current sortOrder <fieldname>|<direction> option, in particular during development when using fast API REST json-server, sort <filedname> and order <direction> must be 2 properties.

By default, splitSortOrder property is false and current behaviour is maintained
Setting splitSortOrder: true in the VueTable.vue properties will create a request using sort and order properties, and url will look like:

    http://localhost:8080/api/items?sort=lastName&order=asc&page=1&perPage=5

Documentation need to be updated to indicates that the 'order' parameter can be also adapted to API endpoint
In the case of json-server , one could use 👍 

    :query-params= "{ sort: '_sort', order: '_order', page: '_page', perPage: '_limit'}"

which will result in an URL like:

        http://localhost:8080/api/items?_sort=lastName&_order=asc&_page=1&_perPage=5

Using splitSorder: true, in case of multiple fields indicated in the sortOrder property, the first field will be selected

### CODE REVIEW

**Comment by ratiw** [comment]
@erwin16 Thanks for the contribution. But you should be able to define your own `getSortParam()` in the parent container to do achieve the same behavior. Please check [this](https://ratiw.github.io/vuetable-2/#/Sorting?id=overriding-the-sort-query-string) out. If not, please let me know.

Also, in the next version, this will be more explicit as functions like `getSortParam` will be replaced by its corresponding `prop` that will accept a function, instead of defining them in the parent container.

**Comment by erwin16** [comment]
Thanks a lot !  Did not found it at first glance ... awesome
 Interesting coming version...  I guess you'll add info in the wiki on what can be defined in the parent container and override the vuetable-2 props 
 i.e data-path, pagination-path, and api-url could be different API endpoints .. (?)

**Comment by erwin16** [comment]
@ratiw OK, I can use the getSortParams() function to get rid of the |<direction> ( and use multipart easily ) but I cannot use it for the direction(s)...
I tried to add it this way:

           getSortParam (sortOrder) {
              const sf = sortOrder.map((sort) => { return sort.field }).join(',')
              const so = sortOrder.map((sort) => { return sort.direction }).join(',')
              return [sf, so].join('&_order=')
          }

but it does not work as expected ,  _order is added to the request, but the & and - characters are escaped ...
       // this does not work...  order is not respected
       http://localhost:8080/api/users?_sort=lastName%26_order%3Dasc&_page=1&_limit=5

       // this works when performed directly on my json-server API
       http://localhost:8080/api/users?_sort=lastName&_order=asc&_page=1&_limit=5

Is there any possibility to add the direction(s) as a function from the sortOrder ? 
thanks for your feedback

**Comment by ratiw** [comment]
@erwin16 I see. Will figure something out.

**Comment by ratiw** [comment]
@erwin16 Just push a modification to the [`develop`](https://github.com/ratiw/vuetable-2/commit/b61e930847685cdded20c733e654ec00a8ad4342) branch aiming to solve your problem.

What I did was allowing `query-params` prop to also accept a Function. This function will
receive `sortOrder`, `currentPage`, and `perPage` as its parameters.

When you define `query-params` as a function, you are responsible to create a key-value
object which contains the query parameters that you would like to be sent to the server
side. In this way, you can completely override the default query string parameters generated
by Vuetable. And you must return this object back, otherwise, Vuetable will not generate
any query string for those options.

```html
<vuetable
  :query-params="queryParams"
></vuetable>
```
```javascript
  //...
  methods: {
    //...
    queryParams (sortOrder, currentPage, perPage) {
      return {
        '_sort': sortOrder[0].name,
        '_order': sortOrder[0].direction,
        '_page': currentPage,
        '_size': perPage
      }
    }
  }
```

**Pull request closed without merging**
