### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by AngeloAnolin**
Update axios reference to remove warnings for NPM Audit.

### CODE REVIEW

**Comment by chiptus** [comment]
is this going to be merged?

**Comment by AngeloAnolin** [comment]
@chiptus - still waiting for @ratiw or any admin to merge the changes. At the moment, I had to manually set this on my package.json on some projects I use vuetable.

**Comment by MarcoVdE** [comment]
@ratiw would you be kind enough to approve this pull request?

**Comment by mannyyang** [comment]
For what it's worth, I have an updated package with this update available to install at `vuetable-3@3.0.3`.

**Pull request closed without merging**
