### PR TITLE
Generate documentation with docsify from wiki pages

### PR DESCRIPTION
**Pull request by cristijora**
Take documentation to the next level. 
Since most of the documentation is written in wiki (markdown), it's pretty easy to generate with tools like docsify or docute some nice website from those markdown files. 
The outcome is something like this:

vuetable-docs

What is left to do is to go into repo settings and choose to serve from master branch docs folder:
steps

After a couple of minutes you can access the site on:
https://ratiw.github.io/vuetable-2/  or something like that.

Development setup:
1. `npm install -g docsify-cli`
2. From repo run `docsify serve ./docs`
3. You will have the website running locally with hot reload

Further info: https://docsify.js.org/#/quickstart

### CODE REVIEW

**Comment by ratiw** [comment]
@cristijora This is so awesome. Thanks for introducing this. :)
Will try to find time to merge this tonight.

**Comment by cristijora** [comment]
Hope it's okay that the target branch is master. The docs would work inside docs folder on master branch or on gh-pages branch so no other option here really.

**Comment by ratiw** [comment]
@cristijora It's ok. Couldn't really ask for more. :)

**Comment by cristijora** [comment]
You need to create a .nojekyll in ./docs to prevent GitHub Pages from ignoring files that begin with an underscore.
I saw that sidebar is not displayed. I think you have to add it in this file since it's a special markdown file but not a page https://docsify.js.org/#/more-pages

**Comment by ratiw** [comment]
Thanks, I'm starting to scratch my mind about this sidebar problem. However, you've already add it in the docs [here](https://github.com/ratiw/vuetable-2/blob/master/docs/.nojekyll). Do I have to do anything else with it? I really have no idea.

**Comment by cristijora** [comment]
Only sidebar from what I know. You can preview this stuff locally and see
how it looks. Also you can install jekyll locally and start it from docs
folder to preview how it will actually look live on github

**Comment by cristijora** [comment]
Try this inside jekyll
```
exclude:
  - _Sidebar.md
```

**Comment by ratiw** [comment]
Ok, renaming `_Sidebar.md` to `_sidebar.md` fix the problem.

**Comment by cristijora** [comment]
Great. Hopefully this will replace wiki pages :)

**Comment by ratiw** [comment]
I will. I will have search and fix all the existing references first though. :)

**Pull request merged**
