### PR TITLE
Add default icon to css

### PR DESCRIPTION
**Pull request by SUKOHI**
I'd like to add functionality to display default icon.
By default, `defaultIcon` is empty in the code.
So we can choose whether we display default icon or not.
I'm glad if you would consider to merge this functionality.
Thank you!

### CODE REVIEW

**Comment by ratiw** [comment]
@SUKOHI Thanks for the PR. However, I do not quite understand why you would need this and how would you picture it to look like?

**Comment by SUKOHI** [comment]
Hi, ratiw.
Thank you for quick reply.

That's because we can easily recognize which column is sortable without color like you did on codepen as an examples.
jQuery's dataTable actually has default icons.
Please see [here](https://datatables.net/) if you don't mind. 

You don't like it?

**Comment by ratiw** [comment]
@SUKOHI Oh, I see. This is fine. Can you please re-submit the PR based on the `develop` branch instead?

**Comment by SUKOHI** [comment]
I see. I created a new PR titled "Add default icon to css #2".
Thank you!

**Pull request closed without merging**
