### PR TITLE
added column widths and fixed header option

### PR DESCRIPTION
**Pull request by rubinsh**
added body and header wrapper css class options.

The purpose of this PR is to provide a height and a fixed header option to vuetable.  
Mainly to address [Issue 178](https://github.com/ratiw/vuetable-2/issues/178).  

I am not exactly sure what you need me to do in order to accept this PR (add docs maybe?) - So I will be more than happy if you could provide some feedback regarding what you need me to do in order for you to merge this pull request (assuming you want it).  

The idea behind the implementation is taken from the markup of [Element's table](http://element.eleme.io/#/en-US/component/table)  where I build one table with only a header and one table with a body - thus allowing fixed scroll without the need for JS.  
But - for the table header and body to be aligned with their column widths I had to add also a "width" option to the fields definition (which I felt that was missing anyway).  

Fixed header is activated when you specify a tableHeight option - then the component renders the content of the table in the given height and makes the header fixed.

I modified the demo app to include a table with a fixedHeader and a height.  
I just starting using your component yesterday and I implemented this today as I could not use the table in my system without having a fixed header.  

Thanks.

### CODE REVIEW

**Comment by ratiw** [comment]
@rubinsh Thank you very much for this PR. Many people have been looking for this feature.

One point that really stops me is that you're using `width` attribute on the `th` and `td`. Since the `width` attribute is [not supported](https://www.w3schools.com/tags/att_td_width.asp) in HTML5 and it is recommended that we use CSS for styling this instead.

**Comment by rubinsh** [comment]
Good point @ratiw - I was not aware that it was deprecated in HTML5.  
I will update my PR to use style attribute (and not CSS) as the width can be determined for each column separately.  
Please let me know if you have other comments regarding the code - I will be happy to fix/explain

**Comment by rubinsh** [comment]
@ratiw - I've updated the code.
I also removed the witdth/style attributes from td elements as they were not needed and kept them only on the th elements and the colgroups elements.

**Comment by rubinsh** [comment]
@ratiw - I rebased the changes from upstream (your origin) to mine and did the merge.  
Seems OK now.  
If you are fine with the changes - please do merge this PR so I won't have to do the merge again next time.  

Thanks!

**Comment by ratiw** [comment]
@rubinsh Would it be possible to just leave out the `style` attribute and just specify the width of each column in the CSS? What do you think?

**Comment by rubinsh** [comment]
@ratiw - I don't think it is possible to programmatically  add css rules.  
Assuming you have 10 different columns with 10 different widths - how will you define it in css?
You could add an option to the column config of something like "columnHeaderCSSClass" and have that option for each column and then set the width in that CSS class but that would be very uncomfortable from the API's perspective...

I modified the code so that the style attribute is only on the th and colspan elements - so performance wise it is OK and there is almost no performance penalty (or none whatsoever) for the inline styles in this case.  

From the API perspective - I think it is much more comfortable and intuitive to just set a "width" attribute for each column as opposed to defining a  columnHeaderCssClass for each column and then write a css rule with the width for each column.  

I am an experienced frontend developer - and I know that in 99% of the cases inline styles are a big no no - but I think that in this case it makes sense to use inline styles.  

Also, using inline styles this way (and not css classes) allows you to programatically change the width of each column from Vue (assuming we would want to have re-sizable columns in the future)

**Comment by ratiw** [comment]
@rubinsh Got it. Will find time to review it a bit and see there is anything that need to be added. Thank you very much for this. :)

**Comment by rubinsh** [comment]
Sure thing.
We will need to add documenation later after you approve, and maybe make
the demo app switch between fixed header and non fixed header in the table
settings.

Thank you for the great component :-)

**Comment by ratiw** [comment]
@rubinsh I'm experiencing problem with column width inconsistency as shown in the following picture.

column width inconsistency in header and body

Something is causing the header to shift more to the right. Have you experiencing this?

**Comment by rubinsh** [comment]
Make sure you a width settings for all the columns.

Also make sure you are on my latest commit.
Which browser are uou using?


On Oct 21, 2017 4:14 PM, "Rati Wannapanop" <notifications@github.com> wrote:

@rubinsh <https://github.com/rubinsh> I'm experiencing problem with column
width inconsistency as shown in the following picture.

[image: column width inconsistency in header and body]
<https://github.com/ratiw/images/raw/master/vuetable-2/column-width-inconsistency.png>

Something is causing the header to shift more to the right. Have you
experiencing this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ratiw/vuetable-2/pull/266#issuecomment-338393632>, or mute
the thread

**Comment by ratiw** [comment]
@rubinsh I am on the latest commit and I'm using Chrome the latest version. After some tinkering, it seems that the problem is not on the header, but actually on the body of the table.

The v-scroll bar seems to cause the table body to shrink to accommodate its size resulting in the table itself adjusting the size by reducing each column size to reflect the changes. When turning `overflow-y` off, the column sizes seems to be ok.

**Comment by rubinsh** [comment]
You are correct.
This can happen if the scrollbar becomes visible and it was not visible
when the table was initially rendered.

What I did when using it in my app is to add the width of the scrollbar to
the last column of the table header if the scrollbar is visible.

I will include this code in the component.
I forgot about this as this was already a few weeks ago.


On Oct 21, 2017 4:43 PM, "Rati Wannapanop" <notifications@github.com> wrote:

@rubinsh <https://github.com/rubinsh> I am on the latest commit and I'm
using Chrome the latest version. After some tinkering, it seems that the
problem is not on the header, but actually on the body of the table.

The v-scroll bar seems to cause the table body to shrink to accommodate its
size resulting in the table itself adjusting the size by reducing each
column size to reflect the changes. When turning overflow-y off, the column
sizes seems to be ok.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ratiw/vuetable-2/pull/266#issuecomment-338395924>, or mute
the thread

**Comment by rubinsh** [comment]
@ratiw - I've updated the code to address the issue you raised.  
Now, when the scrollbar is visible - I add an invisible "gutter" column to solve the column widths offsets.  
When the scrollbar is not visible - the column is removed.  

This is the cleanest solution I could come up with and I'm pretty happy with it.  
I also looked at what other libraries are doing to solve this and it's pretty much the same concept.

**Comment by 4nik4** [comment]
image

I have tried to implement by following the steps (defining width for columns and table height) but I am not getting a desirable outcome. 

One element in field looks like:
`{name: entry[0], title: entry[1].title,  width: "50px"}`

I have passed down the `table-height="600px"`.

Is there something I missed?

**Pull request merged**
