### PR TITLE
Table row classes

### PR DESCRIPTION
**Pull request by lgullestrup**
Assign classes and styling to table rows.

-- i think this was an opps moment.

### CODE REVIEW

**Comment by ratiw** [comment]
@lgullestrup That's quite embarrassing.. but I've done that quite a lot really. :)

**Comment by ratiw** [comment]
However, that doesn't seem to related to the PR's title. Am I missing anything?

**Comment by lgullestrup** [comment]
nope nope. just me failing miserably at github!

**Comment by v1ar31** [comment]
Hello. When will the release of sortableIcon? I do need :)

**Comment by ratiw** [comment]
It's already in the `develop` branch. No target for merging into `master` branch as I still have some features pending.

**Pull request merged**
